export default {
  SET_LOADING_SPINNER: 'SET_LOADING_SPINNER',
  UNSET_LOADING_SPINNER: 'UNSET_LOADING_SPINNER',
  SHOW_MESSAGE: 'SHOW_MESSAGE',
  SET_MESSAGE_TYPE: 'SET_MESSAGE_TYPE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}
