export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_REGISTERED: 'SET_REGISTERED',
  UNSET_REGISTERED: 'UNSET_REGISTERED',
  SHOW_MESSAGE: 'SHOW_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  UNSET_LOGIN_ERROR: 'UNSET_LOGIN_ERROR'
}
