export default {
  SET_TOKEN: 'SET_TOKEN',
  SET_USERNAME: 'SET_USERNAME',
  SET_LOGGED: 'SET_LOGGED',
  UNSET_LOGGED: 'UNSET_LOGGED',
  SET_REGISTERED: 'SET_REGISTERED',
  UNSET_REGISTERED: 'UNSET_REGISTERED',
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  UNSET_LOGIN_ERROR: 'UNSET_LOGIN_ERROR',
  SET_SIGNUP_SERVER_ERROR: 'SET_SIGNUP_SERVER_ERROR',
  UNSET_SIGNUP_SERVER_ERROR: 'UNSET_SIGNUP_SERVER_ERROR',
  SET_USER_TYPE: 'SET_USER_TYPE'
}
